# docker-compose.yml
services:
  frontend: 
    build: ./Frontend
    ports: 
      - 3000:3000
    depends_on:
      - web
  web:
    build: 
      context: .
      dockerfile: battleship/Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./battleship:/code
      - ./game_logic:/code/game_logic
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/  
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  ai-server:
    build: 
      context: .
      dockerfile: ai_server/Dockerfile
    ports:
      - 5555:5555
    depends_on:
      - web
    volumes:
      - ./game_logic:/code/game_logic
      - ./ai_server:/code
  redis:
    image: redis:5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: always

volumes:
  postgres_data:
  redisdata:
