# docker-compose.yml
services:
  frontend: 
    build: ./Frontend
    ports: 
      - 3000:3000
    depends_on:
      - web
  web:
    build: ./battleship
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./battleship:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - ./battleship/postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  ai-server:
    build: ./ai_server
    ports:
      - 7000:7000
    depends_on:
      - web

volumes:
  postgres_data:
