# Generated by Django 5.0.4 on 2024-04-23 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_board', models.CharField(max_length=200)),
                ('attack_board', models.CharField(max_length=200)),
                ('combined_board', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('screen_name', models.CharField(max_length=100)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('num_of_ships_sunk', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board1', models.IntegerField(default=0)),
                ('board2', models.IntegerField(default=0)),
                ('turn', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('num_ships', models.IntegerField(default=0)),
                ('winner', models.IntegerField(default=0)),
                ('loser', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_games', to='shdatabase.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_games', to='shdatabase.player')),
            ],
        ),
    ]
