# Generated by Django 5.0.4 on 2024-05-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_ai_game',
            field=models.BooleanField(default=True),
        ),
    ]
