# Generated by Django 5.0.4 on 2024-05-02 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shdatabase', '0003_player_is_ai_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='board1',
            new_name='board1ID',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='board2',
            new_name='board2ID',
        ),
    ]
