# Generated by Django 5.0.4 on 2024-05-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdatabase', '0004_rename_board1_game_board1id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='size',
            field=models.IntegerField(default=10),
        ),
    ]
