# Generated by Django 5.0.4 on 2024-05-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdatabase', '0005_board_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_hit',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='board',
            name='shot_col',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='board',
            name='shot_row',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_ships',
            field=models.IntegerField(default=4),
        ),
    ]
