# Generated by Django 5.0.4 on 2024-05-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdatabase', '0007_remove_player_password_remove_player_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_ai_player',
            field=models.BooleanField(default=False),
        ),
    ]
